name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller
        
    - name: Build application for macOS
      run: |
        pyinstaller --onefile --windowed \
          --name "CARpetrosani" \
          --add-data "main.ui:." \
          --hidden-import PyQt5.QtWidgets \
          --hidden-import PyQt5.QtCore \
          --hidden-import PyQt5.QtGui \
          main.py
        
    - name: Upload built app
      uses: actions/upload-artifact@v4
      with:
        name: CARpetrosani-MacOS
        path: dist/
