name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        brew update
        # Adaugă libpng pentru PIL/Pillow
        brew install libjpeg zlib libpng
        echo "✅ System dependencies installed"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install openpyxl xlsxwriter reportlab PyQt5 pillow pyinstaller
        # Verificare EXTENSIVĂ a modulelor
        python -c "
        modules = ['openpyxl', 'xlsxwriter', 'reportlab', 'PyQt5', 'PIL']
        for module in modules:
            try:
                __import__(module)
                print(f'✅ {module} imported successfully')
            except ImportError as e:
                print(f'❌ {module} failed: {e}')
        "
        
    - name: Create ICNS from ICO
      run: |
        # Verifică dacă pol.ico există
        if [ ! -f "pol.ico" ]; then
          echo "⚠️  pol.ico not found, creating placeholder..."
          python -c "
          from PIL import Image
          img = Image.new('RGB', (256, 256), color='blue')
          img.save('pol.ico')
          "
        fi
        
        mkdir -p icon.iconset
        python -c "
        from PIL import Image
        img = Image.open('pol.ico')
        sizes = [(16,16), (32,32), (64,64), (128,128), (256,256), (512,512)]
        for i, size in enumerate(sizes):
            resized = img.resize(size, Image.Resampling.LANCZOS)
            resized.save(f'icon.iconset/icon_{size[0]}x{size[1]}.png')
        "
        iconutil -c icns icon.iconset
        cp icon.icns pol.icns
        echo "✅ ICNS created"
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --noconfirm --onedir --windowed \
          --target-arch=universal2 \
          --icon "pol.icns" \
          --name "CARpetrosani" \
          --add-data "fonts:fonts" \
          --add-data "Icons:Icons" \
          --add-data "ui:ui" \
          --add-data "Arial.ttf:." \
          --add-data "DejaVuBoldSans.ttf:." \
          --add-data "DejaVuSans.ttf:." \
          --add-data "DejaVuSans-Bold.ttf:." \
          --hidden-import openpyxl \
          --hidden-import xlsxwriter \
          --hidden-import et_xmlfile \
          --hidden-import reportlab \
          --hidden-import reportlab.lib \
          --hidden-import reportlab.pdfgen \
          --hidden-import reportlab.pdfbase \
          --hidden-import ssl \
          --hidden-import cryptography \
          --hidden-import AppKit \
          --hidden-import Foundation \
          --osx-bundle-identifier "com.petrosani.carapp" \
          main.py
        echo "✅ PyInstaller build completed"
        
    - name: Verify Build Structure
      run: |
        echo "=== Build Verification ==="
        if [ -d "dist/CARpetrosani.app" ]; then
          echo "✅ SUCCES: .app bundle created!"
          echo "=== App Structure ==="
          find "dist/CARpetrosani.app" -type f | head -15
          echo "=== Executable Info ==="
          file "dist/CARpetrosani.app/Contents/MacOS/CARpetrosani"
        else
          echo "❌ FAIL: .app bundle NOT found!"
          echo "=== dist contents ==="
          ls -la dist/
          exit 1
        fi
        
    - name: Fix macOS Security
      run: |
        xattr -cr dist/CARpetrosani.app
        codesign --force --deep --sign - dist/CARpetrosani.app
        echo "✅ Security flags fixed"
        
    - name: Test Basic Functionality
      run: |
        echo "Testing app launch (will timeout after 10s)..."
        timeout 10s dist/CARpetrosani.app/Contents/MacOS/CARpetrosani || echo "✅ App launch test completed"
        
    - name: Create ZIP for easy download
      run: |
        cd dist
        zip -r ../CARpetrosani-macOS-universal.zip CARpetrosani.app
        cd ..
        echo "✅ ZIP created: CARpetrosani-macOS-universal.zip"
        ls -lh CARpetrosani-macOS-universal.zip
        
    - name: Upload ZIP artifact
      uses: actions/upload-artifact@v4
      with:
        name: CARpetrosani-macOS-universal
        path: CARpetrosani-macOS-universal.zip
        retention-days: 30