name : Build macOS App (Apple Silicon)

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        brew update
        brew install libjpeg zlib libpng
        echo "✅ System dependencies installed"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow openpyxl xlsxwriter reportlab PyQt5 pyinstaller
        
        python -c "
        import sys
        modules = ['openpyxl', 'xlsxwriter', 'reportlab', 'PyQt5', 'PIL', 'decimal']
        errors = []
        for module in modules:
            try:
                __import__(module)
                print(f'✅ {module}')
            except ImportError as e:
                print(f'❌ {module}: {e}')
                errors.append(module)
        if errors:
            sys.exit(1)
        print('✅ All modules verified')
        "
        
    - name: Create ICNS from ICO
      run: |
        if [ ! -f "pol.ico" ]; then
          echo "⚠️  pol.ico not found, creating placeholder..."
          python -c "
        from PIL import Image
        img = Image.new('RGB', (256, 256), color='blue')
        img.save('pol.ico')
        "
        fi
        
        mkdir -p icon.iconset
        python -c "
        from PIL import Image
        img = Image.open('pol.ico')
        sizes = [(16,16), (32,32), (64,64), (128,128), (256,256), (512,512)]
        for size in sizes:
            resized = img.resize(size, Image.Resampling.LANCZOS)
            resized.save(f'icon.iconset/icon_{size[0]}x{size[1]}.png')
        "
        iconutil -c icns icon.iconset
        cp icon.icns pol.icns
        echo "✅ ICNS created"
        
    - name: Build for Apple Silicon
      run: |
        rm -rf build dist
        
        echo "Building for Apple Silicon (arm64)..."
        
        pyinstaller --noconfirm --onedir --windowed \
          --icon "pol.icns" \
          --name "CARpetrosani" \
          --add-data "fonts:fonts" \
          --add-data "Icons:Icons" \
          --add-data "Arial.ttf:." \
          --add-data "DejaVuBoldSans.ttf:." \
          --add-data "DejaVuSans.ttf:." \
          --add-data "DejaVuSans-Bold.ttf:." \
          --hidden-import openpyxl \
          --hidden-import openpyxl.cell \
          --hidden-import openpyxl.cell.cell \
          --hidden-import openpyxl.styles \
          --hidden-import openpyxl.styles.numbers \
          --hidden-import openpyxl.utils \
          --hidden-import xlsxwriter \
          --hidden-import xlsxwriter.workbook \
          --hidden-import xlsxwriter.worksheet \
          --hidden-import et_xmlfile \
          --hidden-import reportlab \
          --hidden-import reportlab.lib \
          --hidden-import reportlab.lib.colors \
          --hidden-import reportlab.lib.pagesizes \
          --hidden-import reportlab.lib.units \
          --hidden-import reportlab.pdfgen \
          --hidden-import reportlab.pdfgen.canvas \
          --hidden-import reportlab.pdfbase \
          --hidden-import reportlab.pdfbase.pdfmetrics \
          --hidden-import reportlab.pdfbase.ttfonts \
          --hidden-import ssl \
          --hidden-import decimal \
          --osx-bundle-identifier "com.petrosani.carapp" \
          main.py
        
        echo "✅ Build completed"
        
    - name: Verify Build
      run: |
        echo "=== Build Verification ==="
        
        if [ ! -d "dist/CARpetrosani.app" ]; then
          echo "❌ App bundle NOT found!"
          echo "Contents of dist/:"
          ls -la dist/ || echo "dist/ doesn't exist"
          exit 1
        fi
        
        echo "✅ App bundle exists"
        
        if [ ! -f "dist/CARpetrosani.app/Contents/MacOS/CARpetrosani" ]; then
          echo "❌ Executable NOT found!"
          exit 1
        fi
        
        echo "✅ Executable exists"
        
        echo ""
        echo "=== Architecture ==="
        file "dist/CARpetrosani.app/Contents/MacOS/CARpetrosani"
        lipo -info "dist/CARpetrosani.app/Contents/MacOS/CARpetrosani" || echo "Single architecture"
        
        echo ""
        echo "=== Bundle Size ==="
        du -sh "dist/CARpetrosani.app"
        
        echo ""
        echo "=== Critical Modules Check ==="
        for module in openpyxl xlsxwriter reportlab PyQt5; do
          if find "dist/CARpetrosani.app" -name "*${module}*" -type f | head -1 | grep -q .; then
            echo "✅ $module found in bundle"
          else
            echo "⚠️  $module not found in bundle"
          fi
        done
        
    - name: Fix macOS Security
      run: |
        echo "Removing quarantine attributes..."
        xattr -cr dist/CARpetrosani.app
        
        echo "Applying ad-hoc signature..."
        codesign --force --deep --sign - dist/CARpetrosani.app
        
        echo ""
        echo "=== Signature Verification ==="
        codesign -dv dist/CARpetrosani.app 2>&1 | head -5
        
        echo "✅ Security attributes fixed"
        
    - name: Create Distribution Package
      run: |
        echo "Creating distribution package..."
        
        mkdir -p distribution
        cp -r dist/CARpetrosani.app distribution/
