name: Build macOS App (Apple Silicon)

on:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        brew update
        brew install libjpeg zlib libpng
        echo "✅ System dependencies installed"
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pillow openpyxl xlsxwriter reportlab PyQt5 pyinstaller
        
        # Verificare module
        python -c "
        import sys
        modules = ['openpyxl', 'xlsxwriter', 'reportlab', 'PyQt5', 'PIL']
        for module in modules:
            try:
                __import__(module)
                print(f'✅ {module}')
            except ImportError as e:
                print(f'❌ {module}: {e}')
                sys.exit(1)
        print('✅ All modules verified')
        "
        
    - name: Create ICNS from ICO
      run: |
        if [ ! -f "pol.ico" ]; then
          echo "⚠️  pol.ico not found, creating placeholder..."
          python -c "
        from PIL import Image
        img = Image.new('RGB', (256, 256), color='blue')
        img.save('pol.ico')
        "
        fi
        
        mkdir -p icon.iconset
        python -c "
        from PIL import Image
        img = Image.open('pol.ico')
        sizes = [(16,16), (32,32), (64,64), (128,128), (256,256), (512,512)]
        for size in sizes:
            resized = img.resize(size, Image.Resampling.LANCZOS)
            resized.save(f'icon.iconset/icon_{size[0]}x{size[1]}.png')
        "
        iconutil -c icns icon.iconset
        cp icon.icns pol.icns
        echo "✅ ICNS created"
        
    - name: Build for Apple Silicon
      run: |
        rm -rf build dist
        
        echo "Building for Apple Silicon (arm64)..."
        
        # Build FĂRĂ universal2 - doar pentru arhitectura curentă (arm64)
        pyinstaller --noconfirm --onedir --windowed \
          --icon "pol.icns" \
          --name "CARpetrosani" \
          --add-data "fonts:fonts" \
          --add-data "Icons:Icons" \
          --add-data "Arial.ttf:." \
          --add-data "DejaVuBoldSans.ttf:." \
          --add-data "DejaVuSans.ttf:." \
          --add-data "DejaVuSans-Bold.ttf:." \
          --hidden-import openpyxl \
          --hidden-import openpyxl.cell \
          --hidden-import openpyxl.styles \
          --hidden-import xlsxwriter \
          --hidden-import xlsxwriter.workbook \
          --hidden-import et_xmlfile \
          --hidden-import reportlab \
          --hidden-import reportlab.lib \
          --hidden-import reportlab.lib.colors \
          --hidden-import reportlab.pdfgen \
          --hidden-import reportlab.pdfgen.canvas \
          --hidden-import reportlab.pdfbase \
          --hidden-import reportlab.pdfbase.pdfmetrics \
          --hidden-import reportlab.pdfbase.ttfonts \
          --hidden-import ssl \
          --hidden-import decimal \
          --osx-bundle-identifier "com.petrosani.carapp" \
          main.py
        
        echo "✅ Build completed"
        
    - name: Verify Build
      run: |
        echo "=== Build Verification ==="
        
        if [ ! -d "dist/CARpetrosani.app" ]; then
          echo "❌ .app bundle NOT found!"
          exit 1
        fi
        
        echo "✅ .app bundle created"
        
        # Verifică arhitectura
        echo -e "\n=== Architecture ==="
        file "dist/CARpetrosani.app/Contents/MacOS/CARpetrosani"
        lipo -info "dist/CARpetrosani.app/Contents/MacOS/CARpetrosani"
        
        echo -e "\n=== Size ==="
        du -sh "dist/CARpetrosani.app"
        
    - name: Fix macOS Security
      run: |
        xattr -cr dist/CARpetrosani.app
        codesign --force --deep --sign - dist/CARpetrosani.app
        echo "✅ Security fixed"
        
    - name: Create Distribution
      run: |
        mkdir -p distribution
        cp -r dist/CARpetrosani.app distribution/